#!/usr/bin/env bash
# Script that makes a nginx run as nginx user
pkill apache
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 755 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
