#!/usr/bin/env bash
# add header
sudo apt update
sudo apt install nginx -y

sudo bash -c "echo 'Hello World!' > /var/www/html/index.html"

sudo service nginx start

sudo sed -i '53i\\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

sudo bash -c "echo \"Ceci n'est pas une page\" > /var/www/html/404.html"
sudo sed -i '47i\\n\terror_page 404 /404.html;' /etc/nginx/sites-available/default

sudo sed -i '24i\\n\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default

sudo service nginx restart
