#!/usr/bin/env bash
#Displays a string and on the 9th iteration displays Hi on a new line
count=1
while [ $count -le 10 ]; do
	if [ $count -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done
