#!/usr/bin/env bash
#Displays a string and on the 9th iteration displays Hi on a new line
count=1
while [ $count -le 10 ]; do
	if [ $count -eq 4 ]; then
		echo "bad luck"
	elif [ $count -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
